# CMake script to generate build_info.h with git and timestamp info
# Called during build via execute_process()

# Get git short hash
execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)

# Check if working tree is dirty
execute_process(
    COMMAND git status --porcelain
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_STATUS
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)

if(GIT_STATUS)
    set(GIT_DIRTY 1)
else()
    set(GIT_DIRTY 0)
endif()

# Get UTC timestamp in ISO 8601 format
string(TIMESTAMP BUILD_TIMESTAMP "%Y-%m-%dT%H:%M:%SZ" UTC)

# Generate the header file
file(WRITE ${OUTPUT_FILE}
"// Auto-generated by build_info.cmake - DO NOT EDIT
#ifndef BUILD_INFO_H
#define BUILD_INFO_H

#define BUILD_GIT_HASH \"${GIT_HASH}\"
#define BUILD_GIT_DIRTY ${GIT_DIRTY}
#define BUILD_TIMESTAMP \"${BUILD_TIMESTAMP}\"

#endif // BUILD_INFO_H
")
